// Local
###
GET http://localhost:3000/users

###
POST http://localhost:3000/create-user
Content-Type: application/json

{
  "sub": "auth0|1234567890",
  "given_name": "John"
}

###
GET http://localhost:3000/profile
